# --------------------------- #
# SETTINGS SECTION
# --------------------------- #
SETTINGS:
    # number of concurrent threads
    THREADS: 1

    # number of retries for ANY action
    ATTEMPTS: 5
    
    # account range.
    # BY DEFAULT: [0, 0] - all accounts
    # [3, 5] - only 3 4 5 accounts
    # [7, 7] - only 7 account
    ACCOUNTS_RANGE: [0, 0]
    
    # WORKS ONLY IF ACCOUNTS_RANGE IS [0, 0]
    # exact accounts to use.
    # BY DEFAULT: [] - all accounts
    # Example: [1, 4, 6] - bot will use only 1, 4 and 6 accounts
    EXACT_ACCOUNTS_TO_USE: []
    
    SHUFFLE_WALLETS: true

    # pause between attempts
    PAUSE_BETWEEN_ATTEMPTS: [1, 1]
    
    # pause between swaps
    PAUSE_BETWEEN_SWAPS: [3, 10]
    
    # pause in seconds between accounts
    RANDOM_PAUSE_BETWEEN_ACCOUNTS: [1, 1]
    
    # pause in seconds between actions
    RANDOM_PAUSE_BETWEEN_ACTIONS: [1, 1]
    
    # random pause before start of every account
    # to make sure that all accounts will be started at different times
    RANDOM_INITIALIZATION_PAUSE: [1, 1]
    
    # if true, bot will send logs to telegram
    SEND_TELEGRAM_LOGS: false
    # telegram bot token
    TELEGRAM_BOT_TOKEN: "12317283:lskjalsdfasdfasd-sdfadfasd"
    # telegram users ids
    TELEGRAM_USERS_IDS: [235123432]

    # wait for transaction confirmation in seconds
    WAIT_FOR_TRANSACTION_CONFIRMATION_IN_SECONDS: 120


FLOW:
    # if task from database failed, bot will skip it
    # if false, bot will stop and show error
    SKIP_FAILED_TASKS: false


TOKEN_SENDER:
    # If this feature is true, the bot will send tokens between your wallets, which in theory could link them. 
    # By default, this feature is disabled and the bot sends tokens to random wallets.
    SEND_TOKENS_TO_MY_WALLETS: false

    # Percent of balance to send.
    # BY DEFAULT: [5, 10] - send 5-10% of balance
    PERCENT_OF_BALANCE_TO_SEND: [5, 10]

    # Number of transactions to send.
    # BY DEFAULT: [1, 10] - send 1-10 transactions
    NUMBER_OF_TRANSACTIONS_TO_SEND: [1, 10]


RPCS:
    TEMPO: ["https://rpc.testnet.tempo.xyz"]


OTHERS:
    SKIP_SSL_VERIFICATION: true
    USE_PROXY_FOR_RPC: true
    ENABLE_BROWSER_DASHBOARD: true
